# Generated by Django 6.0.3 on 2026-03-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltopic',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='assessment_icons/'),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='skilltopic',
            name='icon',
            field=models.CharField(default='TOP', max_length=10),
        ),
    ]
