# Generated by Django 5.2.8 on 2026-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=10),
        ),
    ]
