# Generated by Django 5.2.8 on 2026-03-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='CareerCraft', max_length=80)),
                ('tagline', models.CharField(default='Skill-Based Placement Prep Platform', max_length=140)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site branding',
                'verbose_name_plural': 'Site branding',
            },
        ),
    ]
