# Generated by Django 6.0.3 on 2026-03-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='cheatsheet_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='language',
            name='practice_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='language',
            name='tutorial_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.CharField(default='DEV', max_length=10),
        ),
    ]
